export type EmailTemplate = {
  subject: string;
  body: string;
};

export const renderWelcomeEmail = (firstName: string): EmailTemplate => ({
  subject: 'Welcome to HostelGhar',
  body: `Hi ${firstName},\n\nWelcome to HostelGhar. Your account is ready.\n\nRegards,\nHostelGhar Team`,
});

export const renderOwnerCredentialsEmail = (
  firstName: string,
  email: string,
  temporaryPassword: string,
): EmailTemplate => ({
  subject: 'Your HostelGhar owner account is ready',
  body:
    `Hi ${firstName},\n\n` +
    'An owner dashboard account has been created for you.\n\n' +
    `Login email: ${email}\n` +
    `Temporary password: ${temporaryPassword}\n\n` +
    'Please log in and change this password immediately. Do not share these credentials.\n\n' +
    'Regards,\nHostelGhar Team',
});

export const renderPasswordResetEmail = (firstName: string, resetToken: string): EmailTemplate => ({
  subject: 'Reset your HostelGhar password',
  body:
    `Hi ${firstName},\n\n` +
    `Use this password reset token to reset your password:\n\n${resetToken}\n\n` +
    'This token expires in 15 minutes. If you did not request this, ignore this email.\n\n' +
    'Regards,\nHostelGhar Security',
});

export const renderPasswordChangedEmail = (firstName: string): EmailTemplate => ({
  subject: 'Your HostelGhar password was changed',
  body:
    `Hi ${firstName},\n\n` +
    'Your HostelGhar password was changed successfully. If this was not you, contact support immediately.\n\n' +
    'Regards,\nHostelGhar Security',
});

export interface MonthlyFeeBillInput {
  studentName: string;
  studentEmail?: string;
  hostelName: string;
  ownerName: string;
  hostelAddress?: string | null;
  hostelPhone?: string | null;
  hostelEmail?: string | null;
  roomNumber?: string | null;
  nepaliMonthLabel: string;
  nepaliDateLabel: string;
  baseFee: number;
  outstandingDue: number;
  totalPayable: number;
  dueDateAd: string;
  dueDateBs?: string;
  billNo?: string;
}

const npr = (value: number): string =>
  `NPR ${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

export const renderMonthlyFeeBillEmail = (input: MonthlyFeeBillInput): EmailTemplate & { html: string } => {
  const subject = `Hostel Fee Bill — ${input.nepaliMonthLabel} | ${input.hostelName}`;
  const body =
    `Dear ${input.studentName},\n\n` +
    `Your monthly hostel fee bill for ${input.nepaliMonthLabel} (${input.nepaliDateLabel}) has been generated by ${input.hostelName}.\n\n` +
    `Hostel: ${input.hostelName}\n` +
    `Hostel Owner: ${input.ownerName}\n` +
    (input.roomNumber ? `Room: ${input.roomNumber}\n` : '') +
    `\nBase Monthly Fee: ${npr(input.baseFee)}\n` +
    `Previous Outstanding Due: ${npr(input.outstandingDue)}\n` +
    `Total Amount Payable: ${npr(input.totalPayable)}\n` +
    `Due Date (AD): ${input.dueDateAd}\n` +
    (input.dueDateBs ? `Due Date (BS): ${input.dueDateBs}\n` : '') +
    `\nPlease pay before the due date to avoid a late penalty. If you already paid, please ignore this bill.\n\n` +
    `Warm regards,\n${input.ownerName}\n${input.hostelName} Management\n` +
    (input.hostelPhone ? `Phone: ${input.hostelPhone}\n` : '') +
    (input.hostelEmail ? `Email: ${input.hostelEmail}\n` : '');

  const row = (label: string, value: string, strong = false): string =>
    `<tr><td style="padding:10px 14px;color:#475569;font-size:14px;">${escapeHtml(label)}</td>` +
    `<td style="padding:10px 14px;text-align:right;font-size:14px;color:#0f172a;${strong ? 'font-weight:800;' : 'font-weight:600;'}">${escapeHtml(value)}</td></tr>`;

  const html =
    `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;">` +
    `<div style="max-width:640px;margin:0 auto;padding:24px;">` +
    `<div style="background:linear-gradient(135deg,#0f766e,#0ea5e9);border-radius:16px 16px 0 0;padding:24px;color:#fff;">` +
    `<div style="font-size:12px;letter-spacing:2px;opacity:.85;">HOSTELGHAR • MONTHLY FEE BILL</div>` +
    `<h1 style="margin:8px 0 4px;font-size:24px;">${escapeHtml(input.hostelName)}</h1>` +
    `<div style="font-size:14px;opacity:.95;">${escapeHtml(input.nepaliMonthLabel)} • ${escapeHtml(input.nepaliDateLabel)}</div>` +
    `<div style="margin-top:10px;font-size:13px;">Hostel Owner: <strong>${escapeHtml(input.ownerName)}</strong></div>` +
    `</div>` +
    `<div style="background:#fff;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 16px 16px;padding:24px;">` +
    `<p style="margin:0 0 6px;color:#0f172a;font-size:16px;">Dear <strong>${escapeHtml(input.studentName)}</strong>,</p>` +
    `<p style="margin:0 0 16px;color:#475569;font-size:14px;line-height:1.6;">Your monthly hostel fee bill for <strong>${escapeHtml(input.nepaliMonthLabel)}</strong> has been generated. Please find the bill summary below.</p>` +
    `<table style="width:100%;border-collapse:collapse;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">` +
    row('Hostel', input.hostelName) +
    row('Owner', input.ownerName) +
    (input.roomNumber ? row('Room', input.roomNumber) : '') +
    (input.billNo ? row('Bill No', input.billNo) : '') +
    row('Billing Month (BS)', `${input.nepaliMonthLabel} (${input.nepaliDateLabel})`) +
    row('Base Monthly Fee', npr(input.baseFee)) +
    row('Previous Outstanding Due', npr(input.outstandingDue)) +
    row('Total Amount Payable', npr(input.totalPayable), true) +
    row('Due Date (AD)', input.dueDateAd) +
    (input.dueDateBs ? row('Due Date (BS)', input.dueDateBs) : '') +
    `</table>` +
    `<div style="margin:16px 0;padding:14px 16px;border-left:4px solid #f59e0b;background:#fffbeb;border-radius:8px;color:#92400e;font-size:13px;">Please pay before the due date to avoid a late penalty. If you already paid, please ignore this bill.</div>` +
    `<div style="color:#475569;font-size:13px;line-height:1.7;">Warm regards,<br><strong>${escapeHtml(input.ownerName)}</strong><br>${escapeHtml(input.hostelName)} Management` +
    (input.hostelPhone ? `<br>Phone: ${escapeHtml(input.hostelPhone)}` : '') +
    (input.hostelEmail ? `<br>Email: ${escapeHtml(input.hostelEmail)}` : '') +
    `</div>` +
    `</div>` +
    `<div style="text-align:center;color:#94a3b8;font-size:12px;margin-top:14px;">This is an automated HostelGhar billing email. Please do not reply directly.</div>` +
    `</div></body></html>`;

  return { subject, body, html };
};

